import '@/styles/globals.css'
import { Lexend_Deca } from 'next/font/google'
import React from 'react'
import localFont from 'next/font/local'

export const metadata = {
    title: 'Dashboard MAGE 9',
    description: 'Generated by create next app',
}

const lexend = Lexend_Deca({
    subsets: ['latin'],
    weight: ['400', '700', '900'],
})
const airstrike = localFont({
    src: [
        {
            path: '../../public/assets/font/airstrike.woff2',
            weight: '900',
            style: 'normal',
        },
    ],
    variable: '--font-airstrike',
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body
                className={`${lexend.className} ${airstrike.variable} h-screen w-screen bg-mage  bg-cover bg-no-repeat`}
            >
                {children}
            </body>
        </html>
    )
}
